### ISSUE TITLE
It takes ~25 ms to `make_password` or `check_password`

### ISSUE THREAD

**Issue by vasily-kirichenko** [Racum/rust-djangohashers#1]
...in release mode on 4790K CPU. It means it can check 40 passwords per second. Is such performance OK?

**Comment by Racum** [comment]
It is not... I notice that too! :(

1000/40 = 25ms, my machine is a bit older, it takes ~44ms, for comparison, Django here takes ~33ms, granted that hashlib is mostly C code, but still.

The key to optimize that is rust-crypto: or i'm using wrong, or the library is actually slow.

This is my shortcut to call rust_crypto's hmac/sha256/pbkdf2 combo, from `/src/crypto_utils.rs`:

```rust
pub fn hash_pbkdf2_sha256(password: &str, salt: &str, iterations: u32) -> String {
    let mut mac = Hmac::new(Sha256::new(), &password.as_bytes());
    let mut result = [0u8; 32];
    pbkdf2(&mut mac, &salt.as_bytes(), iterations, &mut result);
    result.to_base64(STANDARD)
}
```

It looks fine to me, a few extra str/String casting, but nothing that would impact compared to the actual crypto functions.

I will try [rust-fastpbkdf2](https://github.com/ctz/rust-fastpbkdf2) instead to see I can get better results, if so I'll add to the next version.

**Comment by Racum** [comment]
Well... bad news: [rust-fastpbkdf2](https://github.com/ctz/rust-fastpbkdf2) and [ring](https://github.com/briansmith/ring) both use external libraries (OpenSSL and BoringSSL respectively), looks like rust-crypto is the only pure-Rust implementation, at least, that I could find...

We should try to help [rust-crypto](https://github.com/DaGenix/rust-crypto), starting submitting pull-request with bench tests.

**Comment by chris-morgan** [comment]
Remember that password hashing is *supposed* to be slow, to make cracking infeasible. As computers get faster, the number of iterations is steadily increased so that it’s still slow. So sure, if it’s slower than Django’s implementation then it needs to be made faster, but it is doing stuff that is slow by design.

**Comment by Racum** [comment]
@chris-morgan, yes, i’m familiar with the concept, there should be a time penalty to compare passwords, I think @vasily-kirichenko is concerned about the defender’s penalty being bigger than the attacker’s, since faster implementation already exists.

Researching about PBKDF2, I found this [article/video](https://jbp.io/2015/08/11/pbkdf2-performance-matters/), according to this, there is a way to optimize the function by parallelizing and pre-computing small parts of the algorithm, check [the code](https://github.com/ctz/fastpbkdf2/blob/master/fastpbkdf2.c), I’m not fluent in C, and I'm quite new to Rust to make a site-by-side comparison with [rust-crypto’s PBKDF2](https://github.com/DaGenix/rust-crypto/blob/master/src/pbkdf2.rs), but I believe it should be possible to apply the same optimizations in pure-Rust for rust-crypto.

**Comment by Racum** [comment]
I added an option to use `fastpbkdf2` for pbkdf2 instead of `rust-crypto`, now it is faster than the C-based Python implementation; but since it requires OpenSSL to compile, I kept the `rust-crypto` version as default.

Take a look: https://github.com/Racum/rust-djangohashers#fast-pbkdf2-version
